// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZpraKXkjDOpalyJSggV3FDOpdCbu2e-g',
    appId: '1:566617303342:web:935ef287330c155be7f2bf',
    messagingSenderId: '566617303342',
    projectId: 'flutterapp-a0a08',
    authDomain: 'flutterapp-a0a08.firebaseapp.com',
    storageBucket: 'flutterapp-a0a08.appspot.com',
    measurementId: 'G-284X40WN37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEg0M3SN5c0_wLBG-EHZ-_VJt9ad0nrWk',
    appId: '1:566617303342:android:5e053353a909b291e7f2bf',
    messagingSenderId: '566617303342',
    projectId: 'flutterapp-a0a08',
    storageBucket: 'flutterapp-a0a08.appspot.com',
  );
}
